name: test
on: push
jobs:
  license-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: install deps
        run: npm ci --ignore-scripts
      - name: run check
        run: npm run licenses:check
