name: test
on: push
jobs:
  license-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          registry-url: "https://npm.pkg.github.com"
          scope: "@findy-network"
      - name: install deps
        run: npm ci
      - name: run check
        run: |
          cp ${NPM_CONFIG_USERCONFIG} .
          npm run licenses:check
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
